// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urimcchknfucximjzjgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaW1jY2hrbmZ1Y3hpbWp6amdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Mjc4MzYsImV4cCI6MjA1NzAwMzgzNn0.I-dXSLf87SKgFYKlhhiZJNXXWvfFsJe-sTRfV1qRULE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);