// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzskmxagexfwkwfplslm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6c2tteGFnZXhmd2t3ZnBsc2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTYyNDgsImV4cCI6MjA1NzM3MjI0OH0.Z5GGAkZ_NjI1NzKZ4tcZf-DgF_kiQf0oZ-sFTsUmgK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);